In [109]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt 
import seaborn as sns

In [110]:
data = pd.read_csv('wdi_data.csv')
data['Value'] = pd.to_numeric(data['Value'], errors = 'coerce')
data['Time'] = pd.to_datetime(data['Time'])
data.sort_values(by = ['Country Name', 'Time', 'Series Name'])
data.head(2)

,Country Name,Country Code,Series Name,Series Code,Time,Time Code,Value
0,Bangladesh,BGD,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,1970-01-01 00:00:00.000002025,YR2025,11.424022
1,Bangladesh,BGD,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.ZS,1970-01-01 00:00:00.000002024,YR2024,11.164801

In [111]:
print(f'Number of unique countries: {data['Country Code'].nunique()}')
print(f'Number of lags: {data['Time'].nunique()}')
print(f'Number of Indicators: {data['Series Code'].nunique()}')

Number of unique countries: 9
Number of lags: 50
Number of Indicators: 24

In [112]:
series = pd.DataFrame({'Series' : data['Series Name'].unique()})
series

                                               Series
0   Agriculture, forestry, and fishing, value adde...
1            Exports of goods and services (% of GDP)
2   Foreign direct investment, net inflows (% of GDP)
3                             GDP (constant 2015 US$)
4                               GDP growth (annual %)
5                  GDP per capita (constant 2015 US$)
6                    GDP per capita growth (annual %)
7            Gross fixed capital formation (% of GDP)
8     Gross fixed capital formation (annual % growth)
9   Gross fixed capital formation (constant 2015 US$)
10  High-technology exports (% of manufactured exp...
11           Imports of goods and services (% of GDP)
12  Industry (including construction), value added...
13              Manufacturing, value added (% of GDP)
14       Manufacturing, value added (annual % growth)
15     Manufacturing, value added (constant 2015 US$)
16                                 Population, female
17         Population, female (% of total population)
18                                   Population, male
19           Population, male (% of total population)
20                                  Population, total
21                       Population growth (annual %)
22                   Services, value added (% of GDP)
23                                   Trade (% of GDP)

In [113]:
print('Top countries with the highest maximum foreign investments % of GDP')

(
    data[data['Series Name'] == 'Foreign direct investment, net inflows (% of GDP)']
    .groupby('Country Name')['Value']
    .agg(max_ever_percentage='max', median_percentage = 'median', min_percentage = 'min')
    .sort_values(by='max_ever_percentage', ascending=False)
    .head(5)
)

Top countries with the highest maximum foreign investments % of GDP

              max_ever_percentage  median_percentage  min_percentage
Country Name
Singapore               32.262485          15.268453        3.646085
Viet Nam                11.939483           4.278323       -0.000568
Malaysia                 8.760474           3.501092        0.056692
China                    6.161583           2.149573        0.000045
Philippines              3.122388           1.307479       -0.287668

In [116]:
print('Top countries with the sorted GPD per capita growth')
data[data['Series Name'] == 'GDP per capita growth (annual %)'].groupby('Country Name')['Value']\
.agg(median_growth_percentage = 'median',
     mean_growth_percentage='mean',
     max_growth_percentage='max').sort_values(by = 'median_growth_percentage', ascending = False)

Top countries with the sorted GPD per capita growth

,median_growth_percentage,mean_growth_percentage,max_growth_percentage
Country Name,,,
China,7.630738,7.722661,13.690607
"Korea, Rep.",5.271189,5.282195,11.806326
Viet Nam,5.237177,4.960347,7.725699
Indonesia,4.174277,3.541409,7.286559
Singapore,4.128894,4.074477,14.831461
Malaysia,3.761559,3.378917,8.922229
Bangladesh,3.283302,3.416922,6.972644
Philippines,2.764092,1.970102,6.765954
Japan,1.825062,1.730927,6.341600